
resources_dict = {
     'Account': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'AgingReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'ARRefundCreditCard': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Bill': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Bill payment check': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Bill payment credit card': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Bill to pay': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'BillingRate': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'BudgetSummaryReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'BuildAssembly': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Charge': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Check': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Class': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Company': {'Type': 'Special', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'CompanyActivity': {'Type': 'Special', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Credit card charge': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Credit card credit': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Credit memo': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Currency': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'CustomDetailReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Customer': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Customer message': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Customer type': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'CustomSummaryReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'DataEventRecoveryInfo Event': {'Type': 'Notif.', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'DataEventSubscription Event': {'Type': 'Notif.', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'DataExt': {'Type': 'Special', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'DataExtDef': {'Type': 'Special', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Date-driven terms': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Deposit': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Discount item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Employee': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Entity': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Estimate': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Fixed asset item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'GeneralDetailReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'GeneraSumaryReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Group item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Host application': {'Type': 'Special', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Inventory adjustment': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Inventory assembly item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Inventory item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Invoice': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Item Receipt': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Job type': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'JobReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Journal entry': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'ListDisplay UI': {'Type': 'Integration', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Non-inventory item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Non-wage payroll item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Other charge item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Other name': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Payment item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Payment method': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'PayrollDetailReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'PayrollSummary Report': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Preferences': {'Type': 'Special', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'PriceLevel': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Purchase order': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Receive payment': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Receive payment to deposit': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales order': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales receipt': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales rep': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales tax code': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales tax group item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales tax item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Sales tax payment check': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Service item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Ship method': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'SpecialAccount': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'SpecialItem': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Standard terms': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Subtotal item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Template': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Terms': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Time tracking': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'TimeReport': {'Type': 'Report', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'To do': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'TransactionQuery': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'TxnDisplay UI': {'Type': 'Integration', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'UIEventSubscription Event': {'Type': 'Notif.', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'UIExtensionSubscription Event': {'Type': 'Notif.', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'UnitOfMeasureSet': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Vendor': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Vendor credit': {'Type': 'Txn', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Vendor type': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'Wage payroll item': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False},
     'WorkersCompCode': {'Type': 'List', 'Query': False, 'Add': False, 'Modify': False, 'Delete': False, 'Void': False}
}
