from core.base import QBListBase

class Account(QBListBase):
    def __init__(self,
                 Sublevel: int = None,
                 AccountType: str = None,
                 SpecialAccountType: str = None,
                 AccountNumber: str = None,
                 BankNumber: str = None,
                 Balance: float = None,
                 TotalBalance: float = None,
                 TaxLineRetInfoRet_TaxLineID: int = None,
                 TaxLineRetInfoRet_TaxLineName: str = None,
                 CashFlowClassification: str = None,
                 CurrencyRef_ListID: str = None,
                 CurrencyRef_ListFullName: str = None,
                 ):
        super().__init__(
            list_id=None,
            time_created=None,
            time_modified=None,
            edit_sequence=None,
            data_ext_ret=None,
            name=None,
            full_name=None,
            is_active=None,
            desc=None,
            parent_ref_list_id=None,
            parent_ref_full_name=None,
            sublevel=None)
        ParentRef_ListID: str = None,
        ParentRef_FullName: str = None,
        Sublevel: int = None,
        AccountType: str = None,
        SpecialAccountType: str = None,
        AccountNumber: str = None,
        BankNumber: str = None,
        Balance: float = None,
        TotalBalance: float = None,
        TaxLineRetInfoRet_TaxLineID: int = None,
        TaxLineRetInfoRet_TaxLineName: str = None,
        CashFlowClassification: str = None,
        CurrencyRef_ListID: str = None,
        CurrencyRef_ListFullName: str = None